// A thin wrapper over lucide-react so the comp's string icon names (e.g. the
// dynamic `product.icon`) map to tree-shaken components. Only the icons listed
// here are bundled.

import {
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  ArrowUpDown,
  ArrowUpRight,
  BadgeCheck,
  Ban,
  Bell,
  Cable,
  Check,
  CheckCircle2,
  ChevronDown,
  Clock,
  Coffee,
  CreditCard,
  CupSoda,
  Eye,
  Flame,
  Footprints,
  Heart,
  Home,
  Info,
  Keyboard,
  Lamp,
  LaptopMinimal,
  Layers,
  LayoutGrid,
  Lock,
  Mail,
  MapPin,
  Menu,
  Minus,
  Moon,
  Mouse,
  Package,
  PackagePlus,
  PackageSearch,
  PencilLine,
  PlugZap,
  Plus,
  RefreshCcw,
  RotateCcw,
  Ruler,
  Search,
  SearchX,
  Send,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  Square,
  Star,
  Store,
  Sun,
  Tag,
  TentTree,
  Trash2,
  Truck,
  UserRound,
  Wallet,
  X,
  XCircle,
  Zap,
  type LucideIcon,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  "alert-circle": AlertCircle,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up-down": ArrowUpDown,
  "arrow-up-right": ArrowUpRight,
  "badge-check": BadgeCheck,
  ban: Ban,
  bell: Bell,
  cable: Cable,
  check: Check,
  "check-circle-2": CheckCircle2,
  "chevron-down": ChevronDown,
  clock: Clock,
  coffee: Coffee,
  "credit-card": CreditCard,
  "cup-soda": CupSoda,
  eye: Eye,
  flame: Flame,
  footprints: Footprints,
  heart: Heart,
  home: Home,
  info: Info,
  keyboard: Keyboard,
  lamp: Lamp,
  "laptop-minimal": LaptopMinimal,
  layers: Layers,
  "layout-grid": LayoutGrid,
  lock: Lock,
  mail: Mail,
  "map-pin": MapPin,
  menu: Menu,
  minus: Minus,
  moon: Moon,
  mouse: Mouse,
  package: Package,
  "package-plus": PackagePlus,
  "package-search": PackageSearch,
  "pencil-line": PencilLine,
  "plug-zap": PlugZap,
  plus: Plus,
  "refresh-ccw": RefreshCcw,
  "rotate-ccw": RotateCcw,
  ruler: Ruler,
  search: Search,
  "search-x": SearchX,
  send: Send,
  "shield-check": ShieldCheck,
  shirt: Shirt,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  "sliders-horizontal": SlidersHorizontal,
  sparkles: Sparkles,
  square: Square,
  star: Star,
  store: Store,
  sun: Sun,
  tag: Tag,
  "tent-tree": TentTree,
  "trash-2": Trash2,
  truck: Truck,
  "user-round": UserRound,
  wallet: Wallet,
  x: X,
  "x-circle": XCircle,
  zap: Zap,
};

export interface IconProps {
  name: string;
  size?: number | string;
  color?: string;
  className?: string;
  style?: React.CSSProperties;
}

export function Icon({ name, size = 16, color, className, style }: IconProps) {
  const Cmp = MAP[name] || Square;
  return (
    <Cmp
      size={size}
      color={color}
      strokeWidth={2}
      className={className}
      style={style}
    />
  );
}
